kind: Service
apiVersion: v1
metadata:
  name: "redis"
spec:
  selector:
    app: "ass2"
    service: "redis"
  ports:
    - protocol: "TCP"
      port: 6379
      targetPort: 6379
      nodePort: 30000