kind: Service
apiVersion: v1
metadata:
  name: "web"
spec:
  selector:
    app: "ass2"
    service: "web"
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: LoadBalancer