apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ass2
        service: client
    spec:
      containers:
        - name: client
          image: "rmeany/assignment1:client"