apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: receive
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ass2
        service: receive
    spec:
      containers:
        - name: receive
          image: "rmeany/assignment1:receive"