apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ass2
        service: redis
    spec:
      containers:
        - name: redis
          image: "redis"