apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: sender
  name: sender
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sender
    spec:
      containers:
      - args:
        - ./wait-for-it.sh
        - -t
        - "0"
        - rabbitmq:5672
        - --
        - python
        - OldTwitterClient.py
        image: rmeany/assignment1:client
        name: sender
        resources: {}
      restartPolicy: Always
status: {}
