apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - ./wait-for-it.sh
        - -t
        - "0"
        - rabbitmq:5672
        - --
        - python
        - app.py
        image: rmeany/assignment1:web
        name: web
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
