apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ass2
        service: web
    spec:
      containers:
        - name: web
          image: "rmeany/assignment1:web"